### ISSUE TITLE
Tracker Ticket

### ISSUE THREAD

**Issue by DemHydraz** [TARDIX/ntardix#1]
### Threading

- [ ] Thread signaling (override os.pullEvent, maybe?)
- [ ] Scheduling priority
- [ ] Thread pools
  - [ ] Creation
  - [ ] Isolation
  - [ ] Shared environment (?)
  - [ ] Shared PID (?)

### Filesystem

- [ ] Better mounting
- [ ] Sockets
  - [ ] Local sockets
  - [ ] Rednet sockets (?)
  - [ ] Secure sockets (?)
- [ ] Disk images

### Drivers
- [ ] Device nodes
  - [ ] Modem device node
  - [ ] Printer device node
  - [ ] Monitor device node
- [ ] Virtual terminal
  - [ ] VT over network
  - [ ] VT in monitors

### Executables

- [ ] Dynamic linker
- [ ] Object format
  - [ ] Derivative for executables (?)
- [ ] Maintain a Lua compiler separate of the kernel

### General
- [ ] Kernel graphics library
  - [ ] Optimized drawing
- [ ] Functional programming libraries
- [ ] File-oriented programming libraries

**Comment by jaredallard** [comment]
[ ] Actually Do All of this

**Comment by DemHydraz** [comment]
Well played
